### ISSUE TITLE
Tests are failing for get_field

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/ruby-botan#1]
Creating this issue for tracking purposes.

Assuming this will be merged:
https://github.com/randombit/botan/pull/1027

Then we can clear the cache on Travis and re-run.

**Comment by ronaldtse** [comment]
Great find... Thank you @dewyatt !

**Comment by dewyatt** [comment]
Merge is done, cache has been cleared, botan rebuilt, and all tests are green again.
