### ISSUE TITLE
Add STREEBOG to botan

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/ruby-botan#2]
Botan doesn't contain STREEBOG (GOST R 34.11-2012: Hash Function), and we should add it there before we can do it in ruby-botan.

References:
* [RFC 6986](https://tools.ietf.org/html/rfc6986)
* [STREEBOG Official site](https://www.streebog.net/)

Implementations:
* Open source STREEBOG https://github.com/degtyarevalexey/streebog (BSD 2-clause)

**Comment by dewyatt** [comment]
Streebog made it into the Botan 2.2.0 release (https://github.com/randombit/botan/commit/8bcba33c60056042f2d3a92d58038bbd655a73b8). :)

**Comment by ronaldtse** [comment]
Congratulations and thank you @dewyatt ! 👍
