### ISSUE TITLE
Add STREEBOG

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/ruby-botan#3]
Add STREEBOG to ruby-botan after #2

**Comment by dewyatt** [comment]
Technically we don't need to do anything on the ruby-botan side for this. It will currently work, as long as the installed version of botan is >= 2.2.0:

```ruby
Botan::Digest.new("Streebog-512").hexdigest('some data')
Botan::Digest.new("Streebog-256").hexdigest('some data')
```
