### ISSUE TITLE
Some PK-related tests are failing with newer botan versions

### ISSUE THREAD

**Issue by dewyatt** [riboseinc/ruby-botan#4]
I'll have to look at this when time permits.
It appears to be 6 tests related to PK signatures and verification.

**Comment by dewyatt** [comment]
It looks like the return values for `botan_pk_op_verify_finish` changed from 0/1 to 0/-1 between botan 2.1 and 2.2 (randombit/botan@0d403a38769c07c31ad28bcd1155b513cf695c7a).

Previously I could nicely wrap this [here](https://github.com/riboseinc/ruby-botan/blob/ef9ff054386919b78ccf7952b6f3c11e2aaca8a8/lib/botan/pk/op/verify.rb#L58) and raise an error if rc < 0 [here](https://github.com/riboseinc/ruby-botan/blob/ef9ff054386919b78ccf7952b6f3c11e2aaca8a8/lib/botan/utils.rb#L35).

Not hard to fix but @randombit was this intended in botan? It feels *slightly* strange to me to consider an invalid signature to be an FFI error, but not a big deal (though I guess it breaks backwards-compat).

**Comment by randombit** [comment]
Breaking compat -> it was a bad change. I guess probably the thing to do is revert it, but given the changed return code has already shipped in 2.2 we're kind of boned no matter what.

**Comment by dewyatt** [comment]
Got it...darn, wish I had time to dig into this before the release, but, priorities...
I'll just have to add a version-specific workaround here.

I'll go ahead and file a bug on the botan tracker.
